version: "3"
services:
    ui:
        build:
            context: ./react-frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        container_name: mern-ui
        networks:
            - my-stack-net
        volumes:
            - ./react-frontend/src:/usr/app/src
            - ./react-frontend/public:/usr/app/public
        depends_on:
            - api
        stdin_open: true
        tty: true

    api:
        build:
            context: ./nodejs-backend
            dockerfile: Dockerfile
        environment:
            - MONGODB_URL=mongodb://mongo-db:27017/bashaAiApp
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 3030:3030
        container_name: mern-api
        networks:
            - my-stack-net
        volumes:
            - ./nodejs-backend/src:/usr/app/src
        depends_on:
            db:
                condition: service_started
            redis:
                condition: service_healthy

    db:
        image: mongo:5.0.13
        ports:
            - 27017:27017
        container_name: mongo-db
        networks:
            - my-stack-net
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - my-stack-net
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        command: ["redis-server", "--appendonly", "yes"]
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
            retries: 5

networks:
    my-stack-net:
        driver: bridge

volumes:
    redis-data:
    mongo-data:
        driver: local